"""changed data type of deleted column string to boolean

Revision ID: 1bc0abb96672
Revises: a73a1449fea3
Create Date: 2021-12-16 16:22:23.110321

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1bc0abb96672'
down_revision = 'a73a1449fea3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('call_notes', sa.Column('deleted', sa.Boolean, default=False))
    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('call_notes', 'deleted')
    # ### end Alembic commands ###
