"""add new column deleted to authentication table

Revision ID: 1e47e708a68c
Revises: eaa892455eb5
Create Date: 2021-12-16 16:14:44.139054

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1e47e708a68c'
down_revision = 'eaa892455eb5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'authentication', ['id'])
    op.add_column('call_notes', sa.Column('deleted', sa.String(length=20), nullable=True))
    op.create_unique_constraint(None, 'call_notes', ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'call_notes', type_='unique')
    op.drop_column('call_notes', 'deleted')
    op.drop_constraint(None, 'authentication', type_='unique')
    # ### end Alembic commands ###
