"""changed deleted column to is_deleted

Revision ID: 55c9b6bd19a8
Revises: 1bc0abb96672
Create Date: 2021-12-16 16:50:34.651424

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '55c9b6bd19a8'
down_revision = '1bc0abb96672'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('call_notes', 'deleted', new_column_name='is_deleted', server_default=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('call_notes', sa.Column('deleted', sa.Boolean, default=False))
    # ### end Alembic commands ###
