"""removed deleted columns from the call_notes table

Revision ID: a73a1449fea3
Revises: 1e47e708a68c
Create Date: 2021-12-16 16:18:51.786621

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a73a1449fea3'
down_revision = '1e47e708a68c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('call_notes', "deleted")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('call_notes', sa.Column('deleted', sa.String(length=20), nullable=True))
    # ### end Alembic commands ###
